### ISSUE TITLE
reference to deprecated name "htmltable" in readme. 

### ISSUE THREAD

**Issue by hansthompson** [crubba/htmltab#11]
I was trying to follow a tutorial at 

http://www.r-datacollection.com/blog/Hassle-free-data-from-HTML-tables-with-the-htmltable-package/

but it referenced a package I couldn't find.  I found htmltab and I wasn't completely sure if this was the same thing but renamed or not.

**Comment by crubba** [comment]
htmltable was a predecessor of htmltab. I had to rename because there alright was a htmltable on CRAN.
